### PR TITLE
feat: add getting started button.

### PR DESCRIPTION
**Pull request by musale**
Hi @ProfNandaa ,
I came across this project and was really interested in it. I saw your issues (#27 ) and I managed to add a getting started button on the bot.

**How to test**
Make sure that the firebase read rules are allowed.

Then you do a `POST` to `https://graph.facebook.com/v2.6/me/thread_settings?access_token=YOUR_PAGE_TOKEN` with this kind of payload to get the button on the bot:
```
{
  "setting_type":"call_to_actions",
  "thread_state":"new_thread",
  "call_to_actions":[
    {
      "payload":"USER_DEFINED_PAYLOAD"
    }
  ]
}
```

Then delete the conversation with your `development` bot so that when you initialize a new one, the button will show up.

I noticed there were no tests so I didn't put in any. Kindly check and would really like to hear your feedback.

### CODE REVIEW

**Comment by profnandaa** [comment]
@musale - thanks so much for your contribution. I will go ahead and test and merge this, but I think the PR does more than what's described in the title. They are good features though 👍

**Comment by profnandaa** [comment]
For the _Getting Started_ button, can you add the `.setGetStartedButton(action)` method provided by [BootBot here](https://github.com/Charca/bootbot#setgetstartedbuttonaction)

**Comment by musale** [comment]
@ProfNandaa great! I will look into that ASAP

**Comment by profnandaa** [comment]
I've updated and merged in #33 Thanks for the work!

**Comment by musale** [comment]
@ProfNandaa seen it! You're welcome

**Pull request closed without merging**
